version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/reusable-callers/node/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/reusable-callers/python/"
    schedule:
      interval: "weekly"
