name: Build and deploy Node.js app to Azure Web App - node

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22.x'
      app-name:
        required: true
        type: string
      slot-name:
        required: false
        type: string
        default: 'Production'
      build-command:
        required: false
        type: string
        default: 'npm run build --if-present'
      test-command:
        required: false
        type: string
        default: 'npm run test --if-present'
      client-id:
        required: false
        type: string
      tenant-id:
        required: false
        type: string
      subscription-id:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm ci
        run: npm ci

      - name: Build
        if: ${{ inputs.build-command != '' }}
        run: ${{ inputs.build-command }}

      - name: Test
        if: ${{ inputs.test-command != '' }}
        run: ${{ inputs.test-command }}

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      # - name: Login to Azure
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}


      # - name: 'Deploy to Azure Web App'
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: ${{ inputs.app-name }}
      #     slot-name: ${{ inputs.slot-name }}
      #     package: .
