name: Build and deploy Node.js app to Azure Web App - node

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22.x'
      app-name:
        required: true
        type: string
      slot-name:
        required: false
        type: string
        default: 'Production'
      build-command:
        required: false
        type: string
        default: 'npm run build --if-present'
      test-command:
        required: false
        type: string
        default: 'npm run test --if-present'
      client-id:
        required: false
        type: string
      tenant-id:
        required: false
        type: string
      subscription-id:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: npm install, build, and test
        run: |
          npm install
          ${{ inputs.build-command }}
          ${{ inputs.test-command }}

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49C7A750C3EC45618E333F2FD05DAB8A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_00C0AB5A7BCC4312ADCA171D196DECB3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51E45DE65BC347A8B26A077AE6CDE072 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          package: .
