name: Python Deploy Azure Function

on:
  workflow_call:
    inputs:
      azure_function_app_name:
        required: true
        type: string
        description: 'Azure Function App name'
      python_version:
        required: true
        type: string
        description: 'Python version to use'
      artifact-name:
        required: false
        type: string
        default: 'functionapp.zip'
        description: 'Name of the build artifact to deploy'
      slot-name:
        required: false
        type: string
        default: 'Production'
        description: 'Deployment slot name'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Unzip build artifact
        run: unzip ${{ inputs.artifact-name }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Ensure Azure Function App exists
        run: |
          LOCATION="brazilsouth"
          APP_NAME="${{ inputs.azure_function_app_name }}"
          STORAGE_NAME="${APP_NAME//-/}storage"
          PLAN_NAME="${APP_NAME}-plan"
          RESOURCE_GROUP="${APP_NAME}-rg"
          # Check if Function App exists
          if ! az functionapp show --name "$APP_NAME" --resource-group "$RESOURCE_GROUP" &>/dev/null; then
            echo "Function App $APP_NAME does not exist. Creating..."

            # Create storage account if not exists
            if ! az storage account show --name "$STORAGE_NAME" --resource-group "$RESOURCE_GROUP" &>/dev/null; then
              az storage account create --name "$STORAGE_NAME" --location "$LOCATION" --resource-group "$RESOURCE_GROUP" --sku Standard_LRS
            fi

            # Create a consumption plan if not exists
            if ! az functionapp plan show --name "$PLAN_NAME" --resource-group "$RESOURCE_GROUP" &>/dev/null; then
              az functionapp plan create --name "$PLAN_NAME" --resource-group "$RESOURCE_GROUP" --location "$LOCATION" --sku Y1 --is-linux
            fi

            # Create the Function App
            az functionapp create \
              --name "$APP_NAME" \
              --resource-group "$RESOURCE_GROUP" \
              --plan "$PLAN_NAME" \
              --storage-account "$STORAGE_NAME" \
              --runtime python \
              --runtime-version "${{ inputs.python_version }}" \
              --os-type Linux \
              --functions-version 4
          else
            echo "Function App $APP_NAME already exists."
          fi

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.azure_function_app_name }}
          package: .
          slot-name: ${{ inputs.slot-name }}