name: Python Deploy Azure Function

on:
  workflow_call:
    inputs:
      azure_function_app_name:
        required: true
        type: string
        description: 'Azure Function App name'
      python_version:
        required: true
        type: string
        description: 'Python version to use'
      artifact-name:
        required: false
        type: string
        default: 'functionapp.zip'
        description: 'Name of the build artifact to deploy'
      slot-name:
        required: false
        type: string
        default: 'Production'
        description: 'Deployment slot name'
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Unzip build artifact
        run: unzip ${{ inputs.artifact-name }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.azure_function_app_name }}
          package: .
          slot-name: ${{ inputs.slot-name }}